name: Publish the mkdocs to GitHub Pages

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - uses: actions/configure-pages@v2  

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Build mkdocs
        run: |
          pip install mkdocs mkdocs-material
          ./deploy_website.sh
      
      - uses: actions/upload-pages-artifact@v1
        if: success()
        with:
          path: site

      - name: Deploy to GitHub Pages
        if: success()
        id: deployment
        uses: actions/deploy-pages@main
